version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8080:8080
    networks:
      - spring-mongo-net

  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: product-catalog
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - spring-mongo-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
    depends_on:
      - mongo
    networks:
      - spring-mongo-net

volumes:
  mongodb_data:

networks:
  spring-mongo-net:
    driver: bridge